### ISSUE TITLE
Error 'lgwx_device_mode' 

### ISSUE THREAD

**Issue by MarkusKa** [lorabasics/basicstation#101]
i am trying to build the basicstation on the platform aarch64. however, the error appears when running the makefile:

make platform=aarch64

thanks for help
![Issure](https://user-images.githubusercontent.com/62503243/116218237-a013c200-a74a-11eb-965a-0873c7296b75.PNG)

**Comment by beitler** [comment]
Hello. `platform=aarch64` is not a supported platform as it is not listed in the setup.gmk file.
What is your diff to the clean master?

**Comment by MarkusKa** [comment]
Hello, I have tried to add the architecture to the setup.gmk file. However, I have not been able to get it to work. Now it works with a few changes in the makefile and the architecture of the Rapi.

so with 
make platform=rpi variant=std
