### ISSUE TITLE
Timesync UTC with Local Time

### ISSUE THREAD

**Issue by MarkusKa** [lorabasics/basicstation#102]
Hello all,

How can I synchronise the UTC time of the Basic station with the local time?

I thought it was done automatically by the offset in the src/rt.c file by "rt_utcOffset".

Basicstation: 
![basicstation](https://user-images.githubusercontent.com/62503243/116869219-9c7faf80-ac10-11eb-99a4-c8775911d122.PNG)

Local Time = UTC + 2h
![Time](https://user-images.githubusercontent.com/62503243/116869248-a99c9e80-ac10-11eb-9a32-e3daaccd2acb.PNG)

Thanks for Help

**Comment by beitler** [comment]
Hello. Basic Station does not have a notion of local time. The log line time stamps are always in UTC, which is exactly what you are observing.

**Comment by MarkusKa** [comment]
thanks for the information, so the basic station does not need to be synchronised with the local time.

Then I can close the issue
