### ISSUE TITLE
seqno field in dntxed messages

### ISSUE THREAD

**Issue by RadW2020** [lorabasics/basicstation#119]
Hi, 

I get **_dntxed_** messages like this:

```
{"msgtype":"dntxed","seqno":0,"diid":0,"DR":5,"Freq":868100000,"DevEui":"68-49-B5-28-68-49-B5-28","rctx":0,"xtime":37436176804343530,"txtime":9079.010030,"gpstime":0}
```

But in the documentation, there is nothing regarding the seqno field.

![image](https://user-images.githubusercontent.com/8538542/129735756-73a8cd61-98a3-45ab-aff1-f3723989afd5.png)

is this ok?

**Comment by cstratton** [comment]
If you look in the code, seqno is an old field having similar function to  the current diid

Typically a json parser simply ignores fields it doesn't know about, chances are the goal here is maximum compatibility so I wouldn't worry about it unless you are seeing some specific actual failure which you think might be traced back to this.

**Comment by beitler** [comment]
> If you look in the code, seqno is an old field having similar function to the current diid
> 
> Typically a json parser simply ignores fields it doesn't know about, chances are the goal here is maximum compatibility so I wouldn't worry about it unless you are seeing some specific actual failure which you think might be traced back to this.

This is exactly right. The JSON message parser should ignore unknown/unspecified fields for forward and backward compatibility.
