### ISSUE TITLE
Configuration parameters meaning

### ISSUE THREAD

**Issue by pterodragon** [lorabasics/basicstation#123]
Where do we lookup the meaning of the parameters of say

```
TX_GAIN_LUT Object
{
  "pa_gain" : INT[0..3]
  "dig_gain": INT[0..3]
  "dac_gain": INT[0..3]
  "mix_gain": INT[0..3]
  "rf_power": INT[-128..127]
}
```

?
I'm using SX1302

**Comment by tonysmith55** [comment]
The parameters are the settings for the RF components in the SX1302 baseband receiver and the two SX125* radio chips.  The settings are determined by Semtech and not modified by the user.  
For more detail you can watch Tutorial 30 about Lora by MobileFish.  
https://www.youtube.com/watch?v=WaWca5QfFp0&list=PLmL13yqb6OxdeOi97EvI8QeO8o-PqeQ0g&index=32
