### ISSUE TITLE
RE-OPEN: Problems with Quick Start / s2.sm.tc example

### ISSUE THREAD

**Issue by woobagooba** [lorabasics/basicstation#13]
Issue 11 is not resolved.   

https://github.com/lorabasics/basicstation/issues/11

Please confirm resolutions either by testing yourself or asking the submitter to confirm the fix.

**Comment by acaracas** [comment]
The credentials files cups.key, cups.crt, and cups.trust have to be removed.
Essentially, one would have to try with a clean setup.

**Comment by woobagooba** [comment]
See resolution in #11
