### ISSUE TITLE
CUPS is mandatory?

### ISSUE THREAD

**Issue by otassain** [lorabasics/basicstation#14]

**Comment by otassain** [comment]
Is it possible to use the basic station only with the LNS protocol, without the CUPS part?

**Comment by woobagooba** [comment]
Same question. Many deployments will already have a preferred GW platform management system / protocols in place.

**Comment by beitler** [comment]
CUPS is not mandatory. Since Version 2.0.3 the CUPS engine will not be started if no CUPS credential set is present ([read more](https://doc.sm.tc/station/credentials.html) about credential sets).
