### ISSUE TITLE
Building and implementation Lora-BasicStation on mips architecture

### ISSUE THREAD

**Issue by oziesin** [lorabasics/basicstation#149]
Hi guys,

I am wondering, is there anyone knows how to build Lora BasicStation software package and also how to implement on our own gateway ?

I have hardware that have on onion omega chip so i need to cross compile for mips architecture. I build for linux ubuntu machine x86 architecture but i dont even know what should i do after building.

Any guide for me would be appriciated .

Thanks all.

**Comment by beitler** [comment]
Hi @oziesin, let's continue the discussion [in the forum](https://forum.lora-developers.semtech.com/t/building-and-implementation-lora-basicstation-on-mips-architecture/834).

**Comment by techatreyo** [comment]
Hello,

We are having our own customized hardware with RAK5146 concentrator over SPI bus.

... want to configure gateway to be connected with any LNS with authentication! How should I proceed!!!

OS being used is : "OpenWRT  based Chirpstack gateway OS"
chip : ARM cortex A7
