### ISSUE TITLE
Picocell Gateway is not currently supported

### ISSUE THREAD

**Issue by kuanyili** [lorabasics/basicstation#16]
Although Picocell Gateway is an official Semtech product, it is not yet supported by Basic Station. What is the plan and schedule of support for Picocell Gateway?

**Comment by beitler** [comment]
Support for the Picocell Gateway will be added in one of the next releases.

**Comment by donetdisturb** [comment]
https://www.n-fuse.co/devices/LoRaWAN-Concentrator-Card-mini-PCIe.html
based on
https://www.semtech.com/uploads/documents/picocell_gateway_user_guide.pdf

I hope for a quick implementation, currently it doesn't work ..

**Comment by donetdisturb** [comment]
> Support for the Picocell Gateway will be added in one of the next releases.

Hello @beitler , are there any news about it? Thank you.

**Comment by beitler** [comment]
The next release is in the pipeline and it will add support for the picocell reference design.

**Comment by ogimenez-smtc** [comment]
Hi,

It has been added in release [V2.0.4](https://github.com/lorabasics/basicstation/releases/tag/v2.0.4-9-g3d5c686) and documenation in the [Readme](https://github.com/lorabasics/basicstation#picocell-gateway-linux-os-as-host--sx1308-usb-reference-design) so I close this issue.
