### ISSUE TITLE
Using AWS basic Station,  found TX power to be 0.0dBm

### ISSUE THREAD

**Issue by kilight254** [lorabasics/basicstation#161]
After my test, the power of TX will be 12dBm, the lowest power of SX1301,
I guess there is a server configuration problem or there is a problem with my configuration file, Am I missing something important?
2022-06-22 01:57:17.532 [S2E:INFO] TX ::0 diid=39028 [ant#0] - on air: **925.7MHz 0.0dBm** ant#0(0) DR10 SF10/BW500 frame=20309C905190DF9AD2E59C5E..DE87E47C
![image](https://user-images.githubusercontent.com/86959789/174930468-e4276436-1ebc-4cfd-b8d6-715b2ebe182d.png)

[aws_station.txt](https://github.com/lorabasics/basicstation/files/8953964/aws_station.txt)
[station.txt](https://github.com/lorabasics/basicstation/files/8953972/station.txt)

**Comment by beitler** [comment]
Hi @kilight254 ,

could you please run station with XDEBUG log level (`-l XDEBUG`). This will print the messages from the LNS. We need the content of the `router_config` message as well as the `dnmsg` message of the downlink in order to identify the issue. 

Thanks!

**Comment by kilight254** [comment]
Hi, @beitler [beitler](https://github.com/beitler)

[aws_station.txt](https://github.com/lorabasics/basicstation/files/8955232/aws_station.txt)
Can the TX power of SX1301 be modified in the configuration file?
I looked at the SX1302 Station config, which can do just that.

**Comment by beitler** [comment]
Generally, transmission power is a parameter that is controlled by the LNS. In your case, the LNS sets `max_eirp:0` which explains the behavior that you observe. This might be a misconfiguration issue on the LNS side. 
In the configuration file you can set the `txpow_adjust` value which is the sum of cable loss and antenna gain. `txpow_adjust` is subtracted from the LNS-set TX power before transmitting the packet (see [docs](https://lora-developers.semtech.com/build/software/lora-basics/lora-basics-for-gateways/?url=gw_v1.5.html#rfconf-object)). `txpow_adjust` typically does not change over the lifetime of the gateway, unless of course the antenna is changed.
