### ISSUE TITLE
 BasicStation unable to connect to Chirpstack

### ISSUE THREAD

**Issue by SRagavendar** [lorabasics/basicstation#169]
Hi,
I have ported BasicStation to run on NXP's i.MX platform and initial testing with the simulation using SPI to connect to SX1302 has been successful.
I also have Chirpstack LoRaWAN Server running on another NXP i.MX platform which is in the same local network. Currently I'm facing an issue wherein putting the IP address and port of the Chirpstack Server is not working.
![BasicStation-err1](https://user-images.githubusercontent.com/47320893/190552086-94f14bb1-3625-4c27-8fbe-b3e73b81a719.png)
[Note: There will be extra comments in this log which was to help us to determine the exact reason of the connection refusal.]

We have verified from Chirpstack Server that the websocket is open and ready to accept connections by using  netcat commands to connect directly. 
Is there any way to determine the exact cause of the connection refusal?

**Comment by beitler** [comment]
Hi @SRagavendar ,

the best way to start investigating the issue is to do a TCP packet capture using `tcpdump`. `Connection refused (111)` indicates that the host is reachable but the TCP handshake does not succeed. However, this is contrary to your observation that the connection succeeds using netcat. Did you run netcat on the same host on which you are trying to run station?
Could you post two `tcpdump` captures, one when establishing connection via netcat and one when running station. Based on the packet captures we should see clearly what is going wrong.

**Comment by SRagavendar** [comment]
Hi @beitler, thanks for the reply.
I have captured the packets between the same, 
Here is the tcpdump capture with the one while running the station: [IP address-192.168.1.73, Port-3001]
![tcpdump-MG-19-2](https://user-images.githubusercontent.com/47320893/190957654-2c280441-32dd-41c0-8578-7115e0bf9657.jpeg)
Here I'm able to see that the system running Chirpstack is sending back Ack packets to BasicStation.

And here is the capture while running netcat: [IP address-192.168.1.73, Port-2889]
![tcpdump-MG-NC](https://user-images.githubusercontent.com/47320893/190957900-94cb6f94-b059-428a-b594-6790b75dffba.jpeg)
[Note: in this screenshot both station and netcat captures will be there as I tried them both back-to-back]

I have also attached the captures for your reference

**Comment by SRagavendar** [comment]
The captures are not uploading properly, so I'm attaching the captures as a drive link:
BasicStation TCPDump capture: https://drive.google.com/file/d/1gT6NneMCMO8REer5jqliwinzI0lUX7be/view?usp=sharing
Netcat TCPDump capture: https://drive.google.com/file/d/1qaW1y2mArUbs13QPXELZRiD7tHMBlHqG/view?usp=sharing

**Comment by beitler** [comment]
Thanks for the captures. Indeed the captures indicate that no process is listening on port 3001 on host 192.168.1.73
<img width="1279" alt="image" src="https://user-images.githubusercontent.com/2046752/191581950-910f36eb-a4a0-4612-b1d0-a1063fc8a205.png">

I don't quite understand why you let netcat connect to port 2889. My assumption for this experiment would be that you'd try connecting to same port as station is trying to connect (port 3001) just using netcat. If both, station and netcat behave identically, then the destination host would be at fault. To me there doesn't seem to be anything inherently at fault with LoRa Basics Station here. It really just seems that nothing is listening on port 3001 or a some firewall is preventing the connection to the port.

**Comment by beitler** [comment]
Hi @SRagavendar , 

did you have any luck tracing down why the host did not listen on port 3001?

**Comment by beitler** [comment]
I hope you were able to track down the issue. I will close the issue due to inactivity. Feel free to re-open if it's still relevant.
