### ISSUE TITLE
Use Regional Parameters common name for region?

### ISSUE THREAD

**Issue by brocaar** [lorabasics/basicstation#18]
https://doc.sm.tc/station/tcproto.html

> The field region specifies the region of channel plan and thereby controls certain regulatory behavior such as clear channel assessment as well as duty-cycle and dwell-time limitations. Valid names are compatible with the names of the LoRaWAN Regional Parameters specification, except the end frequency is dropped (e.g., EU863 and US902).

As the LoRaWAN Regional Parameters also provide a common name, wouldn't these be more suitable for `region` values?

![image](https://user-images.githubusercontent.com/165497/55390315-4161c700-5537-11e9-8573-328df23ef10d.png)

**Comment by beitler** [comment]
The conception of the Station protocol predates the definition of the Common Name in the LoRaWAN Regional Parameters. In future releases we will accept both.
