### ISSUE TITLE
DRs array index maps to DR number?

### ISSUE THREAD

**Issue by brocaar** [lorabasics/basicstation#19]
> The field DRs defines the available data rates of the channel plan. It MUST be an array of 16 entries with each entry being an array of three (3) integers encoding the spreading factor SF, the bandwidth BW, and a DNONLY flag. SF MUST be in the range 7..12 for LoRa, or 0 for FSK. BW MUST be one of the numbers 125, 250, 500, and BW is ignored for FSK. DNONLY MUST be 1 if the data rate is valid for downlink frames only, and 0 otherwise.

I make the assumption that the index of the array represents the DR number as specified in the LoRaWAN Regional Parameters, but from the documentation this is not clear. It is also not clear what to do with the unspecified data-rates. From the examples I see that in such a case the SF is set to `-1`, but this is not documented. Both points might be worth adding :)

**Comment by johanstokking** [comment]
>I make the assumption that the index of the array represents the DR number as specified in the LoRaWAN Regional Parameters

Yes. What's confusing here is that this makes the gateway aware of LoRaWAN regional parameters, while they are subject to change and regional parameters are a contract between LNS and device; the gateway plays no role there.

Subject to change is not only adding data rates, but also breaking changes from data rate index to SF/BW values, like what happened in AU915.

So what we do in TTN is that we use the latest PHY version know to NS, and map the incoming data rate index back to that, and then based on the end device's PHY version in question, calculate the real data rate index, which may be different. This would not have been necessary if BS would just send the SF and BW values and didn't care about regional parameters.

**Comment by brocaar** [comment]
I'm doing exactly the same mapping at my side :)

**Comment by woobagooba** [comment]
The situation you've both described appears to make a very unwanted dependency between the BasicStation and Regional Parameters Spec (which as you point out is subject to ongoing changes).  Excellent that you've made the correction assumptions and mapping, but BasicStation should be unambiguously clarified on this point and the dependency removed.  

What do you recommend as specific improvements to resolve this issue?

Thank you

**Comment by brocaar** [comment]
As @johanstokking also proposed, I think too it is better to communicate the data-rate as the actual parameters, instead of the DR numbers.

To remove this dependency, I believe the following payloads would need to change:

* https://doc.sm.tc/station/tcproto.html#radio-meta-data --> `DR`
* https://doc.sm.tc/station/tcproto.html#single-frame-downlink --> `DR`, `RX1DR` and `RX2DR`
* https://doc.sm.tc/station/tcproto.html#multicast-schedule --> `DR`

These DR keys would then be replaced by the modulation type + parameters related to this modulation (bandwidth, spreading factor, ...).

**Comment by johanstokking** [comment]
Agreed; adding fields is also fine not to break API.

**Comment by woobagooba** [comment]
What say Semtech on this point?

**Comment by rbaldwin13** [comment]
In an effort to improve our customer support experience and in recognition that our support backlog on GitHub has historically exceeded the capacity of our engineering team, we have taken the difficult decision to focus on the most contemporary issues reported and to close all others without confirmation of resolution.

Our belief is that issues which have remained unresolved and unaltered for extended periods of time are less likely to continue to pose a significant problem to the user than when they were originally filed. More contemporary issues however may still be relevant and hence are more appropriate to prioritize.

For those users who remain interested in resolution of a reported issue that was closed, we are encouraging usage of our developer portal forums [https://forum.lora-developers.semtech.com/] and commercial support portal [https://semtech.force.com/ldp/ldp_support] as the preferred avenues to receive support. We will continue to monitor the GitHub issue trackers as well, but want to encourage all users to take advantage of the increased community presence on the developer portal. For commercial customers, we highly recommend using the commercial support portal which is uniquely tailored to service such support requests.
