### ISSUE TITLE
STATION_REPO

### ISSUE THREAD

**Issue by b1r63r** [lorabasics/basicstation#2]
In the readme, add a line to set STATION_REPO before using it in the instructions.
Also, I had to reset my RAK 831 with this little script before starting station, so perhaps add it to the repo or instructions?
```
#!/bin/bash 
echo "17" > /sys/class/gpio/export 
echo "out" > /sys/class/gpio/gpio17/direction 
echo "1" > /sys/class/gpio/gpio17/value 
sleep 5 
echo "0" > /sys/class/gpio/gpio17/value 
sleep 1 
echo "0" > /sys/class/gpio/gpio17/value 

```
Otherwise this seems to have worked fine on my rpi/RAK 831. Now I am just wondering what the next steps are to get my gateway onto the map.

**Comment by beitler** [comment]
Triggering a reset sequence before starting up the radio is required as part of radio initialization by many platforms. This is why you can set your platform-specific reset script in the `radio_init` field of the configuration file ([check out the documentation](https://doc.sm.tc/station/conf.html#radio-configuration) for more details). This script is executed by Station just before the radio is started. 

Note, that in a multi-board setup where multiple boards are exposed as separate SPI devices, the radio boards are handled by corresponding individual slave processes. Therefore, you need to have one radio_init script per board and configure each in the corresponding slave-X.conf configuration file ([in the documentation](https://doc.sm.tc/station/gw_v1.5.html#multi-board-sample-configuration) you will find more details about the support for multi-board setups).

We will update the docs and eliminate any unclarity with respect to the STATION_REPO variable.
