### ISSUE TITLE
FSK channel configuration options missing in documentation?

### ISSUE THREAD

**Issue by brocaar** [lorabasics/basicstation#20]
https://doc.sm.tc/station/tcproto.html#router-config-message

```text
{
  "radio_0": { .. } // same structure as radio_1
  "radio_1": {
    "enable": BOOL,
    "freq"  : INT
  },
  "chan_FSK": {
    "enable": BOOL
  },
  "chan_Lora_std": {
    "enable": BOOL,
    "radio": 0|1,
    "if": INT,
    "bandwidth": INT,
    "spread_factor": INT
  },
  "chan_multiSF_0": { .. }  // _0 .. _7 all have the same structure
  ..
  "chan_multiSF_7": {
    "enable": BOOL,
    "radio": 0|1,
    "if": INT
  }
}
```

The only documented option for `chan_FSK` is the `enable` key. I would expect to also be able to set the `if`, `radio`, ... Are these implemented but missing in the documentation?

**Comment by beitler** [comment]
Thanks for spotting this. I fixed the doc now. Of course, the `chan_FSK` object requires the `radio` and `if` fields, as well.
