### ISSUE TITLE
Handling proprietary MType

### ISSUE THREAD

**Issue by brocaar** [lorabasics/basicstation#24]
https://doc.sm.tc/station/tcproto.html#lorawan-proprietary-frames

```text
{
  "msgtype"   : "propdf",
  "FRMPayload": "HEX",
  ..
}
```

> Frames marked as proprietary are forwarded in the following form, whereby the entire **frame payload** is passed along uninterpreted.

Does frame payload in this context mean the complete `PHYPayload` or the `PHYPayload` without the `MHDR`? As I don't think "frame payload" within the context of `MType=Proprietary` is specified by the LoRaWAN specification, this line might need some additional wording in the documentation.

In case it would be the latter (thus remaining bytes after the `MHDR`), then please note that you would lose the `Major` field information.

![image](https://user-images.githubusercontent.com/165497/55720464-30b2c480-5a01-11e9-99b7-dac0a5502d63.png)

(In general, I would have preferred to just receive an uplink `PHYPayload`, without the Basic Station splitting this out by `MType` and `PHYPayload` fields.)

**Comment by brocaar** [comment]
Thanks for the confirmation. This might be worth adding to the documentation :)

**Comment by rbaldwin13** [comment]
In an effort to improve our customer support experience and in recognition that our support backlog on GitHub has historically exceeded the capacity of our engineering team, we have taken the difficult decision to focus on the most contemporary issues reported and to close all others without confirmation of resolution.

Our belief is that issues which have remained unresolved and unaltered for extended periods of time are less likely to continue to pose a significant problem to the user than when they were originally filed. More contemporary issues however may still be relevant and hence are more appropriate to prioritize.

For those users who remain interested in resolution of a reported issue that was closed, we are encouraging usage of our developer portal forums [https://forum.lora-developers.semtech.com/] and commercial support portal [https://semtech.force.com/ldp/ldp_support] as the preferred avenues to receive support. We will continue to monitor the GitHub issue trackers as well, but want to encourage all users to take advantage of the increased community presence on the developer portal. For commercial customers, we highly recommend using the commercial support portal which is uniquely tailored to service such support requests.
