### ISSUE TITLE
Handling LoRaWAN 1.1 Rejoin requests?

### ISSUE THREAD

**Issue by brocaar** [lorabasics/basicstation#25]
LoRaWAN 1.1 specifies a RejoinRequest `MType`. Is it correct that this `MType` is not (yet) supported by the Basic Station?

![image](https://user-images.githubusercontent.com/165497/55721384-85efd580-5a03-11e9-8786-3bf90d87dc56.png)

![image](https://user-images.githubusercontent.com/165497/55721432-aae44880-5a03-11e9-8ec3-002b331530d7.png)

![image](https://user-images.githubusercontent.com/165497/55721484-c6e7ea00-5a03-11e9-95e8-bd78b92f909b.png)

**Comment by rbaldwin13** [comment]
In an effort to improve our customer support experience and in recognition that our support backlog on GitHub has historically exceeded the capacity of our engineering team, we have taken the difficult decision to focus on the most contemporary issues reported and to close all others without confirmation of resolution.

Our belief is that issues which have remained unresolved and unaltered for extended periods of time are less likely to continue to pose a significant problem to the user than when they were originally filed. More contemporary issues however may still be relevant and hence are more appropriate to prioritize.

For those users who remain interested in resolution of a reported issue that was closed, we are encouraging usage of our developer portal forums [https://forum.lora-developers.semtech.com/] and commercial support portal [https://semtech.force.com/ldp/ldp_support] as the preferred avenues to receive support. We will continue to monitor the GitHub issue trackers as well, but want to encourage all users to take advantage of the increased community presence on the developer portal. For commercial customers, we highly recommend using the commercial support portal which is uniquely tailored to service such support requests.
