### ISSUE TITLE
Support for polarization inversion flag

### ISSUE THREAD

**Issue by brocaar** [lorabasics/basicstation#26]
We are using `MType=Proprietary` to broadcast messages between gateways for discovery / collecting meta-data. For normal gateway to device use-cases the polarization-inversion ([iPol](https://github.com/Lora-net/packet_forwarder/blob/master/PROTOCOL.TXT#L364)) field must be set to true. For communication between gateways, we set this to false.

Is or will this be possible with the Basic Station? This field doesn't seem to be exposed looking at the documentation.

**Comment by brocaar** [comment]
Potentially this could be done by adding a field which defaults to `true` (for downlink) when not specified in the JSON. When it is defined in the JSON (LNS to Basic Station), then then its value will be used so that it can be set to false.

That way it would be fully optional and backwards compatible.

**Comment by rbaldwin13** [comment]
In an effort to improve our customer support experience and in recognition that our support backlog on GitHub has historically exceeded the capacity of our engineering team, we have taken the difficult decision to focus on the most contemporary issues reported and to close all others without confirmation of resolution.

Our belief is that issues which have remained unresolved and unaltered for extended periods of time are less likely to continue to pose a significant problem to the user than when they were originally filed. More contemporary issues however may still be relevant and hence are more appropriate to prioritize.

For those users who remain interested in resolution of a reported issue that was closed, we are encouraging usage of our developer portal forums [https://forum.lora-developers.semtech.com/] and commercial support portal [https://semtech.force.com/ldp/ldp_support] as the preferred avenues to receive support. We will continue to monitor the GitHub issue trackers as well, but want to encourage all users to take advantage of the increased community presence on the developer portal. For commercial customers, we highly recommend using the commercial support portal which is uniquely tailored to service such support requests.
