### ISSUE TITLE
Unify EUI encoding

### ISSUE THREAD

**Issue by brocaar** [lorabasics/basicstation#27]
Currently the EUIs are being encoded (both from Basic Station to LNS as LNS to Basic Station) as either ID6, EUI or integer.
Some example:

https://doc.sm.tc/station/tcproto.html#querying-the-lns-connection-end-point-discovery
`router` can be either `ID6`, `EUI` or `integer` encoded:

```
{
  "router": ID6 | EUI | integer
}
```

The response is expected as `ID6`

```
{
  "router": ID6,
  "muxs"  : ID6,
  "uri"   : "URI",
  "error" : STRING   // only in case of error
}
```

https://doc.sm.tc/station/tcproto.html#router-config-message
The `JoinEui` is `integer` encoded:

```
{
  "msgtype"    : "router_config"
  "NetID"      : [ INT, .. ]
  "JoinEui"    : [ [INT,INT], .. ]  // ranges: beg,end inclusive
  "region"     : STRING             // e.g. "EU863", "US902", ..
  "hwspec"     : STRING
  "freq_range" : [ INT, INT ]       // min, max (hz)
  "DRs"        : [ [INT,INT,INT], .. ]   // sf,bw,dnonly
  "sx1301_conf": [ SX1301CONF, .. ]
  "nocca"      : BOOL
  "nodc"       : BOOL
  "nodwell"    : BOOL
}
```

https://doc.sm.tc/station/tcproto.html#lorawan-join-requests

Here the `JoinEui` and `DevEui` are `eui` encoded:

```
{
  "msgtype" : "jreq",
  "MHdr"    : UINT,
  "JoinEui" : EUI,
  "DevEui"  : EUI,
  "DevNonce": UINT,
  "MIC"     : INT32,
  ..
}
```

---

For a future version, it would be great if these encodings can be unified into a single encoding as it would make it easier to implement the protocol :slightly_smiling_face:

**Comment by woobagooba** [comment]
I am going to agree with Orne and Johan.  Consolidate this usage of ID6, EUI-64 and integers.  It is adding complexity for reasons which appear to be driven by reduction in message size.  If that is the case, instead of trying various clever ways to reduce message text size, it would be better that a binary object encoding be considered.   The text encoding will be an issue you will hear from those BasicStation users paying monthly sell backhaul bills.

**Comment by rbaldwin13** [comment]
In an effort to improve our customer support experience and in recognition that our support backlog on GitHub has historically exceeded the capacity of our engineering team, we have taken the difficult decision to focus on the most contemporary issues reported and to close all others without confirmation of resolution.

Our belief is that issues which have remained unresolved and unaltered for extended periods of time are less likely to continue to pose a significant problem to the user than when they were originally filed. More contemporary issues however may still be relevant and hence are more appropriate to prioritize.

For those users who remain interested in resolution of a reported issue that was closed, we are encouraging usage of our developer portal forums [https://forum.lora-developers.semtech.com/] and commercial support portal [https://semtech.force.com/ldp/ldp_support] as the preferred avenues to receive support. We will continue to monitor the GitHub issue trackers as well, but want to encourage all users to take advantage of the increased community presence on the developer portal. For commercial customers, we highly recommend using the commercial support portal which is uniquely tailored to service such support requests.
