### ISSUE TITLE
Hidden exception

### ISSUE THREAD

**Issue by ma11** [lorabasics/basicstation#28]
The exception raised on [this line](https://github.com/lorabasics/basicstation/blob/master/pysys/id6.py#L304) is silently hidden by the `except: pass` bloc on [this line](https://github.com/lorabasics/basicstation/blob/master/pysys/id6.py#L306)

**Comment by beitler** [comment]
Nice catch. This will be fixed in the next release. Thanks.

**Comment by ogimenez-smtc** [comment]
Hi,

Fixed by 817e6e1, release V2.0.4.
I am closing this issue.
