### ISSUE TITLE
Undocumented RADIO_INIT_WAIT parameter

### ISSUE THREAD

**Issue by gotthardp** [lorabasics/basicstation#36]
Initialization of some radios take longer than 200ms. There is an undocumented RADIO_INIT_WAIT parameter, which can be used to increase this number. The "radio_init" works as lowercase, but "RADIO_INIT_WAIT" seem to work as uppercase, which is a bit confusing.

The following works for me
```
"station_conf": {
...
   "radio_init": "./reset_lgw.sh start",
   "RADIO_INIT_WAIT": 500
}
```

**Comment by beitler** [comment]
Basic Station allows to change a number of low-level parameters at runtime, `RADIO_INIT_WAIT` being one of them. The `-p` option prints all those parameters. Each of these parameters has some platform-specific default value defined in [src/s2conf.h](https://github.com/lorabasics/basicstation/blob/c29b8502f8c715daecec6666835da6e981dc820a/src/s2conf.h#L152-L181). The parameter values can be overwritten via environment variables or appropriate entries in station.conf - as you did in your case. 
It's true that this feature may deserve more coverage in the documentation. We will update it in due course.
