### ISSUE TITLE
Compatibility with sx1302_hal

### ISSUE THREAD

**Issue by AkDmOl** [lorabasics/basicstation#47]
Hi!
Is this Basic Station compatible with [libloragw](https://github.com/Lora-net/sx1302_hal ) for sx1302?

**Comment by beitler** [comment]
Hi!
The current release pre-dates the release of the sx1302_hal [0] and the Corecell [1] reference design based on the SX1302. Therefore, this release does not support it. However, the next release will add compatibility with the sx1302_hal.

[0] https://github.com/Lora-net/sx1302_hal
[1] https://www.semtech.com/company/press/semtech-releases-indoor-reference-design-for-smart-buildings-and-homes

**Comment by AkDmOl** [comment]
Okay, Thank you!
