### ISSUE TITLE
st2pkfwd without python3.6

### ISSUE THREAD

**Issue by AkDmOl** [lorabasics/basicstation#49]
Hi!

I'm new to Lora things, so, likely, it's not an issue and I just can't read documentation properly, but for me it's a bit confusing.
Are there any ways to use Basic Station(on hardware) with existing network server implementations which support the pkfwd protocol without porting python3.6 to the board, as it mentioned in st2pkfwd example?
If not, could you please help me and tell the minimum version(release) of LNS, which supports Basic Station features or provide me with helpful links concerning implementation LNS&CUPS+Basic Station?

Thank you in advance!

**Comment by mullerch** [comment]
ChirpStack supports LNS : https://www.chirpstack.io/
The TTN stack v3 does also : https://thethingsstack.io/

**Comment by ogimenez-smtc** [comment]
Hi,

You can also use TTN V2: https://www.thethingsnetwork.org/docs/gateways/basics-station/
