### ISSUE TITLE
Git clone instructions in README.md are incorrect

### ISSUE THREAD

**Issue by kersing** [lorabasics/basicstation#5]
README.md contains:
```git clone https://github.com/lorabasics/station.git $STATION_REPO```
This should be
```git clone https://github.com/lorabasics/basicstation.git $STATION_REPO```

**Comment by beitler** [comment]
Thanks, we will fix that.

**Comment by woobagooba** [comment]
Same issue here .... https://github.com/lorabasics/basicstation

To avoid duplicated text and errors, reference your main documentation at https://doc.sm.tc/station/ and just put a minimal overview in the README

**Comment by beitler** [comment]
Corrected in the latest release.
