### ISSUE TITLE
Fix error when CFG_prod is set

### ISSUE THREAD

**Issue by robertlie** [lorabasics/basicstation#54]
When CFG_prod is set, I get an error message in sys_linux.c.
Fix:
case J_device_mode: {
LOG(MOD_S2E|WARNING, "Feature not supported in production level code (station.conf) - ignored: %s", **D.field.name**);
uj_skipValue(**&D**);
break;
}

**Comment by beitler** [comment]
Thanks for reporting this issue. It is fixed in the upcoming release.

**Comment by ogimenez-smtc** [comment]
Hi,

Fixed by 817e6e1, release V2.0.4.
I am closing this issue.
