### ISSUE TITLE
US915 implementation for Linux or Pi --  femto ETA?

### ISSUE THREAD

**Issue by billversteeg** [lorabasics/basicstation#61]
I see from previous comments that there is a plan to support the Semtech femto gateway hardware.

Is there an ETA for this? If not, is there a sample solution for North American channel plans? I do have a couple of the Kerlink gateways that I could target, but would prefer to use a Linux or PI platform. 

If you need help getting the femto running on Linux, please let me know. I may be able to help out.

thanks in advance, this is great stuff.....

Bill VerSteeg

**Comment by beitler** [comment]
Hello Bill,
if you still need support for particular platforms, please let me know - or ideally work directly with the gateway vendor.
