### ISSUE TITLE
v2.0.5 License

### ISSUE THREAD

**Issue by mullerch** [lorabasics/basicstation#64]
The license was removed in the last release.

I can't see any licencing information. Can you tell us more about this change, why it occurred and if the new version can still be distributed ?

Thanks in advance for the clarification.

**Comment by reissjason** [comment]
Also requesting license clarification.

**Comment by anandsingh3** [comment]
Now License are embedded in all the source files.
The License is same as earlier i.e.  "--- Revised 3-Clause BSD License ---"

**Comment by reissjason** [comment]
It is unfortunately not easy to integrate the embedded license with a build tools such as bitbake. The separate LICENSE file is pretty standard in opensource repos.

**Comment by mullerch** [comment]
Thanks for the clarification. I agree with reissjason, you should keep it standard it will help all of us using automated tools.
