### ISSUE TITLE
lns-ttn - error

### ISSUE THREAD

**Issue by symovs** [lorabasics/basicstation#65]
Hello

Am not able to run the example. Am using the corecell design in India and for using the India frequency plan I had set the tc.uri file content to wss://lns.in.thethings.network:443. Am getting the following error

![image](https://user-images.githubusercontent.com/66220236/84577357-29dbca80-add9-11ea-8836-9b9fcd9c74ac.png)

pls help in solving it.

**Comment by beitler** [comment]
The error message reads
![image](https://user-images.githubusercontent.com/2046752/151862498-1cc617dd-70fd-4466-a136-f163d84c30c7.png)
I don't have anything to add to that. Please check the station.conf file and inspect the router_config message coming from the LNS (use `-l AIO:XDEBUG` for low-level IO logging)
