### ISSUE TITLE
How can I change the Heartbeat (LastSeen) interval of TTN gateway

### ISSUE THREAD

**Issue by HIMANSHUSTAR8** [lorabasics/basicstation#73]

**Comment by beitler** [comment]
Station does not send any application-level heartbeat.
The "LastSeen" metric exposed by TTN is extracted based on TTN-internal heuristics, probably using the time of the last received uplink through that gateway. Another, probably more robust, option to determine connection status is to use the TCP connection state. Station sets up TCP keep alive by default, giving the server a robust indication of connection status without requiring application level heartbeats.
