### ISSUE TITLE
Build for linux/debian and arm64?

### ISSUE THREAD

**Issue by BenediktMiller** [lorabasics/basicstation#75]
Hello,

I am trying to use basicstation on arm64 but if I try Linux as the platform the compiler complains that I have the wrong arch. Is there any way to run on arm64 or any getting started on adding arm64 support myself?

**Comment by beitler** [comment]
The platforms defined in this repository are not meant to be exhaustive. arm64 support is certainly possible and has been done before. Check out this work for example:
https://github.com/mpous/basicstation/blob/master/setup.gmk
