### ISSUE TITLE
Is this a bug?

### ISSUE THREAD

**Issue by mjstudio** [lorabasics/basicstation#79]
I am wondering if 
check_dnfreq(s2ctx, D, &txjob->rx2freq, &txjob->dnchnl);
should be check_dnfreq(s2ctx, D, &txjob->rx2freq, &txjob->**_dnchnl2_**);
in the following function?

void handle_dnmsg (s2ctx_t* s2ctx, ujdec_t* D) {
... ...
        case J_Freq:
        case J_RX1Freq: {
            check_dnfreq(s2ctx, D, &txjob->freq, &txjob->dnchnl);
            flags |= 0x0200;
            break;
        }
        case J_RX2DR: {
            check_dr(s2ctx, D, &txjob->rx2dr);
            flags |= 0x0400;
            break;
        }
        case J_RX2Freq: {
            _**check_dnfreq(s2ctx, D, &txjob->rx2freq, &txjob->dnchnl);**_
            flags |= 0x0800;
            break;
        }
...
}

**Comment by ogimenez-smtc** [comment]
Hi,

You are right it seems to be an issue, we will confirm it and correct it if required
