### ISSUE TITLE
CUPS is a confusing name

### ISSUE THREAD

**Issue by jpmeijers** [lorabasics/basicstation#8]
Let's try and use a different name for the update and configuration server and protocol. CUPS is the name of a unix printing server. We're causing a lot of headaches for everyone by using this same name. Googling for CUPS will give results for the more common one, which is the printing server.

**Comment by beitler** [comment]
Though SEO is not our primary concern, I agree with you that most people will associate the CUPS acronym with the Common Unix Printing System. From today's perspective it's not very likely that we will see large demand for printing-enabled LoRa Gateways in the future. Therefore, we can safely assume that talking about CUPS in the context of LoRa Gateways will not cause a lot of confusion.
Nevertheless, we value your feedback and will consider changing the name of the [Credentials and Update Management Protocol](https://doc.sm.tc/station/cupsproto.html) to something less ambiguous.

**Comment by woobagooba** [comment]
Groan ... https://blogs.cisco.com/sp/mwc-series-ultra-packet-core-with-cups-to-deliver-5g-broadband-services-for-stc

**Comment by rbaldwin13** [comment]
In an effort to improve our customer support experience and in recognition that our support backlog on GitHub has historically exceeded the capacity of our engineering team, we have taken the difficult decision to focus on the most contemporary issues reported and to close all others without confirmation of resolution.

Our belief is that issues which have remained unresolved and unaltered for extended periods of time are less likely to continue to pose a significant problem to the user than when they were originally filed. More contemporary issues however may still be relevant and hence are more appropriate to prioritize.

For those users who remain interested in resolution of a reported issue that was closed, we are encouraging usage of our developer portal forums [https://forum.lora-developers.semtech.com/] and commercial support portal [https://semtech.force.com/ldp/ldp_support] as the preferred avenues to receive support. We will continue to monitor the GitHub issue trackers as well, but want to encourage all users to take advantage of the increased community presence on the developer portal. For commercial customers, we highly recommend using the commercial support portal which is uniquely tailored to service such support requests.
