### ISSUE TITLE
Inconsistent naming - what is the official name of BasicStation?

### ISSUE THREAD

**Issue by lnlp** [lorabasics/basicstation#86]
To my understanding the official name was BasicStation.

However, I see the following three different names being used:

- BasicStation
- Basic Station
- LoRa Basics™ Station

I see similar differences for BasicMAC, Basic MAC and LoRa Basics™ MAC.

From repository name perspective the correct name appears to be BasicStation (or 'Basic Station').
Or in full: LoRa Basics' BasicStation.

'LoRa Basics™ Station' looks like some marketing afterthought and appears incorrect from both repository name and technical perspectives; BasicStation is a LoRaWAN gateway, not a LoRa gateway.
While 'LoRa Basics™' appears to be an unregistered trademark, 'LoRa Basics™ Station' appears not to be any trademark.

So which one is it? Which name is correct and can we please have some more consistency?

**Comment by beitler** [comment]
The official name is **LoRa Basics™ Station**. For historic reasons, you may find references to 'Basic Station' which is not the official name anymore.

**Comment by lnlp** [comment]
Thanks.
