### ISSUE TITLE
USB based SX1302

### ISSUE THREAD

**Issue by chrissnow** [lorabasics/basicstation#89]
I'm trying to use this with a SX1302CSS868GW1 which is USB based, however this requires libloragw 2 or later.
Basicstation for SX1302 seems to be fixed on 1.0.5 so this isn't currently possible I don't think?

**Comment by ogimenez-smtc** [comment]
Hi,

USB based Corecells are not currently supported by Basics Station, it is on the road map but we do not have any date to share yet.
